### ISSUE TITLE
KBD Error regenerating an image

### ISSUE THREAD

**Issue by Adrien-Rivas** [seapath/yocto-bsp#17]
Hi,

I'm currently trying to install seapath and i have an error when i try to regenerate an image (or when i try to do a cqfd -b all). The execution allways end with an error code 1. The image is generated on a fresh debian 11 installation in a virtual machine and update/upgrade are done. The behavior is the same with Ubuntu 18.04. 

The df-h command show a 83% free space on a 250GB disk

```
| ERROR: Execution of '/home/adrien/projet/build/tmp/work/corei7-64-poky-linux/kbd/2.2.0-r0/temp/run.do_compile.739434' failed with exit code 1
ERROR: Task (/home/adrien/projet/sources/poky/meta/recipes-core/kbd/kbd_2.2.0.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3180 tasks of which 2078 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 4 seconds
```

For regenerating a new image after trying to get a "all" flavor i deleted the project folder and redo a repo sync, cqfd init and make a cqfd task, and i could generate a host_efi flavor but not a flash_efi.

You can find attached the seapath_install.txt (list of command done for install or reinstall project) file, the cat_errorlog.txt (outpout of the run.do_compile.739434) file and the all-outpout-console.txt (console outpout during generating cqfd projet) file and the poky logfile failure.
[all-outpout-console.txt](https://github.com/seapath/yocto-bsp/files/8212891/all-outpout-console.txt)
[cat_errorlog.txt](https://github.com/seapath/yocto-bsp/files/8212893/cat_errorlog.txt)
[Seapath_Install.txt](https://github.com/seapath/yocto-bsp/files/8212894/Seapath_Install.txt)
[poky_failure.txt](https://github.com/seapath/yocto-bsp/files/8212951/poky_failure.txt)

Thanks in advance.

Adrien

**Comment by dupremathieu** [comment]
Hi Adrien,

It is a known issue: https://github.com/seapath/meta-seapath/issues/51 it occurred with kbd and libvirt.

The workaround is to clean the packet and rebuild.
To clean kbd for the flash-efi image you can use the command:
`cqfd run ./build.sh -v -i seapath-flash-efi --distro seapath-flash --machine votp-flash  -- bitbake -c cleansstate kbd`

**Comment by Adrien-Rivas** [comment]
Hi Mathieu and thanks for your answer,

Ok i will test this.

Another issue, when i try to generate a cqfd -b host_efi_dbg (for acces with a login / pwd account for example) i met this error

NOTE: Tasks Summary: Attempted 2522 tasks of which 0 didn't need to be rerun and all succeeded.
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 6 seconds
NOTE: [Hardening]: done
WARNING: Path /home/adrien/Documents/mon_projet/build/security/manifests/20220309093149 does not exist. Archiving is skipped
ERROR: Command execution failed: Stopped build


And I can't generate the file. It seems happening after generating the ceph. I launched the cqfd -b host_efi to see if it generate a kbd error and if I have to launch the cleansstate command.

And I don't know if it's normal, but the host_efi command don't generate the qcow2 file for the hypervisor host, i only got qcow2 file for guests hosts

Thanks.

Adrien

**Comment by dupremathieu** [comment]
For the error I can't say anything without more logs but if it occurred during Ceph build it have probably failed due to an out of memory error. Ceph take a lot of memory when building.

There is an option in SEAPATH to limit the number of Ceph building jobs to avoid this error. In the SEAPATH root directory, copy the file seapath.conf.sample in seapath.conf and modify the SEAPATH_PARALLEL_MAKE to limit the Ceph building jobs.

`cqfd -b host_efi` to not generate a qcow2 image because host images is for physical hypervisor machine and the qcow2 is a VM disk format.

It is possible to generate host images which can be used in a complete virtual environment to test SEAPATH with seapath-guest-host images. There is no cqfd flavor to generate its, but we can do it with cqfd run:
* For seapath-guest-host-bios-image: `cqfd run ./build.sh -v -i seapath-guest-host-bios-image`
* For seapath-guest-host-bios-image-dbg: `cqfd run ./build.sh -v -i seapath-guest-host-bios-image-dbg --distro seapath-host-cluster-minimal.conf`

**Comment by Adrien-Rivas** [comment]
Hi Mathieu and thanks for your answer, it was very helpfull.

If i can permit, the good command was `cqfd run ./build.sh -v -i seapath-guest-host-bios-dbg-image`

I tried the full command `cqfd run ./build.sh -v -i seapath-guest-host-bios-dbg-image --distro seapath-host-minimal.conf` but the script return me following error 
`ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
Following is the list of potential problems / advisories:
DISTRO 'seapath-host-minimal.conf' not found. Please set a valid DISTRO in your local.conf`

It seems the attendeed command is `cqfd run ./build.sh -v -i seapath-guest-host-bios-dbg-image --distro seapath-host-minimal` (I have currently a running image generation with the command without the .conf extention).

I will put the generated qcow2 file in a KVM and will see if I encount any issue. If not I close this issue.

Many thanks for your help.

Kind Regards.

Adrien
