### ISSUE TITLE
OVS settings lost on reboot

### ISSUE THREAD

**Issue by PengRspace** [seapath/yocto-bsp#18]
Hi,

We are now testing the settings of openvswitch OVS on a votp-host deployed by image of SeaPath, and we have got an issue of OVS settings lost on reboot.

For example, we have created a bright with 'ovs-vsctl add-br' or 'ovs-vsctl add-port', after that we can also see our news settings by 'ovs-vsctl show'. 

But, once we reboot our votp-host, all that settings will be lost.

One more issue about the sysctl settings, we have found that on our votp-host there is no file sysctl.conf in /etc, but there is a file 99-sysctl-network.conf in /etc/sysctl.d. 
If we want to change the setting of 'net.ipv4.ip_forward' from 0 to 1, command 'sysctl -w net.ipv4.ip_forward=1' works, but this setting will be lost too on reboot. 
But if we add one line 'net.ipv4.ip_forward = 1' in /etc/sysctl.d/99-sysctl-network.conf, even after a reboot, this setting will still be saved. Is this normal for you ?

Thanks in advance.

Best regards,

Peng

**Comment by dupremathieu** [comment]
Hi Peng,

SEAPATH come with the systemd service votp-config_ovs.service to configure Open vSwitch. This service can enter in conflict with OVS configuration done manually.
I suggest you to first disable this service and see if it solves the issue. It can be done with the command: `systemctl disable votp-config_ovs.service`

In SEAPATH like other distribution using systemd-sysctl.service, sysctl settings are defined through files in /usr/lib/sysctl.d/, /run/sysctl.d/, and /etc/sysctl.d/.
See https://man7.org/linux/man-pages/man5/sysctl.d.5.html for details.
So adding 'net.ipv4.ip_forward = 1' in /etc/sysctl.d/99-sysctl-network.conf or in a custom file in /etc/sysctl.d/ will work.

IP forwarding can also be control by [systemd-networkd](https://www.freedesktop.org/software/systemd/man/systemd.network.html#IPForward=).

**Comment by PengRspace** [comment]
Hi Mathieu,

We have confirmed that it works after the disable of votp-config_ovs.service.

Thanks for helping.

Best regards

Peng

**Comment by dupremathieu** [comment]
Good news.

If it seems good for you, can you please close the issue?
