### ISSUE TITLE
FW_FR launch failed

### ISSUE THREAD

**Issue by PengRspace** [seapath/yocto-bsp#19]
Hi,

In our votp-host, we have tried to deploy a VM of FW_FR which was defined by a xml file with content like the one attached below.
[FW_FR.txt](https://github.com/seapath/yocto-bsp/files/8351355/FW_FR.txt)

Status IP:
votp-host:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:75:72:67 brd ff:ff:ff:ff:ff:ff
    inet 172.31.2.196/24 brd 172.31.2.255 scope global dynamic enp0s9
       valid_lft 2174sec preferred_lft 2174sec
3: enp0s10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:c5:7d:8d brd ff:ff:ff:ff:ff:ff
    inet 172.31.3.163/24 brd 172.31.3.255 scope global dynamic enp0s10
       valid_lft 2174sec preferred_lft 2174sec
4: enp0s11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:55:72:67 brd ff:ff:ff:ff:ff:ff
5: enp0s12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:09:a6:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.217/24 brd 192.168.100.255 scope global dynamic enp0s12
       valid_lft 2175sec preferred_lft 2175sec
6: enp0s13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:0e:75:2d brd ff:ff:ff:ff:ff:ff
7: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:50:1c:ab brd ff:ff:ff:ff:ff:ff
    inet 172.31.1.12/24 brd 172.31.1.255 scope global dynamic enp0s3
       valid_lft 34574sec preferred_lft 34574sec
8: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
9: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
10: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
11: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0

And the interface enp0s9 was defined with virsh net-define enp0s9.xml.
[enp0s9.txt](https://github.com/seapath/yocto-bsp/files/8351667/enp0s9.txt)

But when we tried to launch it, we got:

votp-host:~$ sudo virsh net-start enp0s9
error: Failed to start network enp0s9
error: cannot write to /proc/sys/net/ipv6/conf/virbr0/disable_ipv6 to enable/disable IPv6 on bridge virbr0: Read-only file system

And, it seems that the VM FW_FR can't be launched for it:

votp-host:~$ virsh start FW_FR
error: Failed to start domain FW_FR
error: Requested operation is not valid: network 'enp0s9' is not active

Then, we tried to add virbr0 and enp0s9 in OVS like below:
votp-host:~$ sudo ovs-vsctl show
e6638c18-7855-46e0-ae42-f0574d61302f
    Bridge virbr0
        Port virbr0
            Interface virbr0
                type: internal
        Port enp0s9
            Interface enp0s9
    ovs_version: "2.15.2"

The error message of 'net-start' was changed like:
votp-host:~$ sudo virsh net-start enp0s9
error: Failed to start network enp0s9
error: error creating bridge interface virbr0: File exists

So, could you please help us to figure out how to fix it ?

Thanks in avance.

Best regards

Peng

**Comment by dupremathieu** [comment]
Hi,
The syntax in enp0s9.txt and FW_FR.txt are both incorrect.

There are two ways to use an OVS with libvirt:
* create the bridge port outside libvirt and use the <interface type="ethernet"> to attach it  in libvirt (this is what is done in SEAPATH by default)
* let libvirt create the ports

Here you have mixed the two ways.

SEAPATH only support the first way, if you want libvirt create the ports you have to remove
"ProtectKernelTunables=yes" in /lib/systemd/system/libvirtd.service.

**Comment by PengRspace** [comment]
Hi Mathieu,

Just, how to attach the bright port outside libvirt for this VM, please ?

Thanks.

**Comment by PengRspace** [comment]
I have added this 5 lines in my FW_FR.xml, and defined with virsh define.

But when I tried to start this VM, I got an error below:

votp-host:~/stockage_pool$ virsh start FW_FR
error: Failed to start domain FW_FR
error: Unable to create tap device enp0s9: Invalid argument

**Comment by PengRspace** [comment]
Hi Mathieu,

Could you please give us a little help to launch this VM proprely ?
So, I just reopen it for a moment.

Thanks in avance.

Peng

**Comment by eroussy** [comment]
Close as outdated
