### ISSUE TITLE
Build failure (system-config)

### ISSUE THREAD

**Issue by salerio-gs** [seapath/yocto-bsp#2]
I am trying to build using the supplied instructions i.e. cqfd init, cqfd run and I am getting the error below.

```
ERROR: system-config-1.0-r0 do_fetch: Can't find ssh public key. Put your ssh public key in "yocto-bsp/keys/ansible_public_ssh_key.pub".
ERROR: Logfile of failure stored in: /build1/peter/SEAPATH/yocto-bsp/build/tmp/work/all-poky-linux/system-config/1.0-r0/temp/log.do_fetch.30644
ERROR: Task (/build1/peter/SEAPATH/yocto-bsp/sources/meta-seapath/recipes-votp/system-config/system-config.bb:do_fetch) failed with exit code '1'

```

It seems as if I need a key, have I missed where this is documented or is this a bug?

**Comment by dupremathieu** [comment]
Yes, you need to put our ssh public key in "yocto-bsp/keys/ansible_public_ssh_key.pub". See  https://github.com/seapath/yocto-bsp/blob/master/keys/README.adoc.

**Comment by salerio-gs** [comment]
Thx, I will close this and reopen if  required.
