### ISSUE TITLE
cqfd warning

### ISSUE THREAD

**Issue by PengRspace** [seapath/yocto-bsp#20]
Hi,

We had recently got an error when we tried to create an image for a seapth-guest with commands 'cqfd run ./build.sh -v -i seapath-guest-host-bios-image --distro seapath-guest -- bitbake -c cleansstate kbd'.

Error message like below :
 
NOTE: Fetching uninative binary shim http://downloads.yoctoproject.org/releases/uninative/3.5/x86_64-nativesdk-libc-3.5.tar.xz;sha256sum=e8047a5748e6f266165da141eb6d08b23674f30e477b0e5505b6403d50fbc4b2 (will check PREMIRRORS first)
NOTE: [Hardening]: started
Initialising tasks: 100% |####################################################################################################################| Time: 0:00:01
Sstate summary: Wanted 0 Found 0 Missed 0 Current 0 (0% match, 0% complete)
NOTE: No setscene tasks
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 2 tasks of which 0 didn't need to be rerun and all succeeded.
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 5 seconds
NOTE: [Hardening]: done
WARNING: Path /seapath/build/security/manifests/20220408144724 does not exist. Archiving is skipped

Summary: There were 4 WARNING messages shown.
Summary: There were 9 ERROR messages shown, returning a non-zero exit code.

Could you help us to resolved it, please ?

Thanks in advance.

Best regards,

Peng

**Comment by eroussy** [comment]
close as outdated
