### ISSUE TITLE
Add resize2fs to resize persistent partition

### ISSUE THREAD

**Issue by esguti** [seapath/yocto-bsp#24]
**Is your feature request related to a problem? Please describe.**
There is no tool for resizing persistent partition on host

**Describe the solution you'd like**
Add resize2fs on host image

**Describe alternatives you've considered**
There is no alternative to resize partition to occupy all free space on host disk

**Additional context**
There is also no way to install the tool

**Comment by Paullgk** [comment]
Hello!
Since PR https://github.com/seapath/meta-seapath/pull/178 persistent partition is now extended during flash with the maximum free space available on disk.
